### ISSUE TITLE
Comment tu fais pour être trop fort ?

### ISSUE THREAD

**Issue by Mr-R-b0t** [PouletteMC/L3N-Java-Project#1]
Bonjour monsieur, 

J'aimerais savoir comment tu fais pour être aussi fort ?

Dans l'attente de votre réponse. 

Sébastien

**Comment by PouletteMC** [comment]
C'est avant tout un gros manque de sommeil et une bonne dose de connerie

**Comment by Mr-R-b0t** [comment]
Grand respect a vous alors mon chère monsieur...
